// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kridbhyhprwhpcglgrnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyaWRiaHlocHJ3aHBjZ2xncm5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MzM4NDcsImV4cCI6MjA3MDIwOTg0N30.Bg9YdfQeSC42or2jusAH9Q25TBRFe-vuC9D4wHqHVe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});